~/De/graduation-project-/fl-service/ap/inventory main ?1 > ansible-playbook -i inventory.yaml playbook.yaml -vvvv                                               11s py fl-service-mVGCKuWe-py3.10 03:52:09
ansible-playbook [core 2.14.4]
  config file = None
  configured module search path = ['/Users/nevzatseferoglu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nevzatseferoglu/Library/Caches/pypoetry/virtualenvs/fl-service-mVGCKuWe-py3.10/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/nevzatseferoglu/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/nevzatseferoglu/Library/Caches/pypoetry/virtualenvs/fl-service-mVGCKuWe-py3.10/bin/ansible-playbook
  python version = 3.10.7 (v3.10.7:6cc6b13308, Sep  5 2022, 14:02:52) [Clang 13.0.0 (clang-1300.0.29.30)] (/Users/nevzatseferoglu/Library/Caches/pypoetry/virtualenvs/fl-service-mVGCKuWe-py3.10/bin/python)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /Users/nevzatseferoglu/Desktop/graduation-project-2/fl-service/app/inventory/inventory.yaml as it did not pass its verify_file() method
script declined parsing /Users/nevzatseferoglu/Desktop/graduation-project-2/fl-service/app/inventory/inventory.yaml as it did not pass its verify_file() method
Parsed /Users/nevzatseferoglu/Desktop/graduation-project-2/fl-service/app/inventory/inventory.yaml inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /Users/nevzatseferoglu/Library/Caches/pypoetry/virtualenvs/fl-service-mVGCKuWe-py3.10/lib/python3.10/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: playbook.yaml ***********************************************************************************************************************************************************************************
Positional arguments: playbook.yaml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/Users/nevzatseferoglu/Desktop/graduation-project-2/fl-service/app/inventory/inventory.yaml',)
forks: 5
1 plays in playbook.yaml

PLAY [My first play] **************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************
task path: /Users/nevzatseferoglu/Desktop/graduation-project-2/fl-service/app/inventory/playbook.yaml:2
<suav@192.168.1.105> ESTABLISH SSH CONNECTION FOR USER: None
<suav@192.168.1.105> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/Users/nevzatseferoglu/.ansible/cp/f4168dc313"' suav@192.168.1.105 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<suav@192.168.1.105> (255, b'', b'OpenSSH_8.6p1, LibreSSL 3.3.6\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files\r\ndebug1: /etc/ssh/ssh_config line 54: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.1.105 is address\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts\' -> \'/Users/nevzatseferoglu/.ssh/known_hosts\'\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts2\' -> \'/Users/nevzatseferoglu/.ssh/known_hosts2\'\r\ndebug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/nevzatseferoglu/.ansible/cp/f4168dc313" does not exist\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to 192.168.1.105 [192.168.1.105] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x48\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 192.168.1.105 port 22: Operation timed out\r\nssh: connect to host 192.168.1.105 port 22: Operation timed out\r\n')
fatal: [rm01]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_8.6p1, LibreSSL 3.3.6\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files\r\ndebug1: /etc/ssh/ssh_config line 54: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.1.105 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/nevzatseferoglu/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/nevzatseferoglu/.ssh/known_hosts2'\r\ndebug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/nevzatseferoglu/.ansible/cp/f4168dc313\" does not exist\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to 192.168.1.105 [192.168.1.105] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x48\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 192.168.1.105 port 22: Operation timed out\r\nssh: connect to host 192.168.1.105 port 22: Operation timed out",
    "unreachable": true
}

PLAY RECAP ************************************************************************************************************************************************************************************************
rm01                       : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0